### ISSUE TITLE
Secondary namenodes for HDFS

### ISSUE THREAD

**Issue by zzvara** [gchq/gaffer-docker#180]
Dear Maintainer and Community,

After spending hours looking for a canonical and recent HDFS Helm chart I'm very happy that I have found this repository.
I was able to install it easily. Encountered the following error(?), nevertheless, it works:

```
2021-07-02 17:16:23,850 INFO ipc.Server: IPC Server handler 5 on default port 8021, call Call#213 Retry#0 org.apache.hadoop.hdfs.server.protocol.DatanodeProtocol.registerDatanode from 10.233.82.216:51320
org.apache.hadoop.hdfs.server.protocol.DisallowedDatanodeException: Datanode denied communication with namenode because hostname cannot be resolved (ip=10.233.82.216, hostname=10.233.82.216): DatanodeRegistration(0.0.0.0:9866, datanodeUuid=85c1fa7a-398e-4046-a8d0-8879240b5f37, infoPort=9864, infoSecurePort=0, ipcPort=9867, storageInfo=lv=-57;cid=CID-d32a905e-e427-46ce-b058-68978ba6ecb8;nsid=128164394;c=1625245633356)
	at org.apache.hadoop.hdfs.server.blockmanagement.DatanodeManager.registerDatanode(DatanodeManager.java:1026)
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.registerDatanode(BlockManager.java:2452)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.registerDatanode(FSNamesystem.java:3913)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.registerDatanode(NameNodeRpcServer.java:1538)
	at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolServerSideTranslatorPB.registerDatanode(DatanodeProtocolServerSideTranslatorPB.java:101)
	at org.apache.hadoop.hdfs.protocol.proto.DatanodeProtocolProtos$DatanodeProtocolService$2.callBlockingMethod(DatanodeProtocolProtos.java:31660)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
```

I noticed that there is no secondary-namenode deployment option. Is it planned or an open issue for contribution?

Thanks,
Zoltán

**Comment by t92549** [comment]
Hi Zoltán,

Apologies on getting back to you so late!
This isn't something we have had requests for before but I can see why it would be useful. If it is a feature you would like implemented then I suppose it is an open issue for contribution.

It seems that something similar could be done with the `values.yaml` perhaps if you just want more replicas:

https://github.com/gchq/gaffer-docker/blob/a44df2db5289262ef974d8ba2ee235d9dabc5911/kubernetes/hdfs/values.yaml#L54-L55

We are always grateful for contributions! Apologies again though on taking so long to get back. Any other features or improvements you want to see, feel free to open a ticket and submit a PR.

**Comment by ctas582** [comment]
Hi,

Glad to hear that you've found our Helm chart easy to use :)

We've encountered similar errors to the one you have posted. We believe it is caused by DNS lookups being performed before a pod/container has been registered into the cluster's DNS service. Unfortunately, it appears the underlying DNS client caches these failed lookups so you may find that some datanodes are unable to register with the namenode even after the DNS entry has been created. However, the check can be disabled by setting `dfs.namenode.datanode.registration.ip-hostname-check=false` in the HDFS config.

We don't have any plans to support deploying a secondary namenode, but would be happy to accept contributions from the community. We currently use resilient data volumes for the namenode (e.g. EBS, Ceph) and rely on Kubernetes' native features to detect namenode failures to restart it or migrate it to another node.

**Comment by n3101** [comment]
This question appears to have been answered

**Comment by t92549** [comment]
I agree the original question was answered, but if @zzvara does want to see this implemented then feel free to reopen this or make a new issue and state that you'd like to implement this feature. Cheers
